### ISSUE TITLE
Tried setting "useMockServer: true" in karma.conf.js but got   Error: Uncaught ReferenceError: module is not defined    node_modules/karma-openui5/lib/mockserver.js:9

### ISSUE THREAD

**Issue by yonggao** [SAP/karma-openui5#4] opened 2015-12-10 01:03 UTC

**Comment by matz3** [comment] 2015-12-15 13:17
Could you please share your complete `karma.conf.js` so that we can reproduce the issue. Thanks!

**Comment by yonggao** [comment] 2016-01-14 07:44
// Karma configuration
// Generated on Thu Aug 06 2015 16:48:51 GMT+0800 (China Standard Time)

module.exports = function (config) {
  config.set({

    // base path that will be used to resolve all patterns (eg. files, exclude)
    basePath: './',


    // frameworks to use
    // available frameworks: https://npmjs.org/browse/keyword/karma-adapter
    frameworks: ['qunit', 'openui5'],

    browserNoActivityTimeout: 1000000,

    openui5: {
      path: 'https://sapui5.hana.ondemand.com/resources/sap-ui-core.js',
      useMockServer: true
    },


    // list of files / patterns to load in the browser, skipped here
    files: [],


    // list of files to exclude
    exclude: [],


    // preprocess matching files before serving them to the browser
    // available preprocessors: https://npmjs.org/browse/keyword/karma-preprocessor
    preprocessors: {},


    // test results reporter to use
    // possible values: 'dots', 'progress'
    // available reporters: https://npmjs.org/browse/keyword/karma-reporter
    reporters: ['progress'],


    // web server port
    port: 9876,


    // enable / disable colors in the output (reporters and logs)
    colors: true,


    // level of logging
    // possible values: config.LOG_DISABLE || config.LOG_ERROR || config.LOG_WARN || config.LOG_INFO || config.LOG_DEBUG
    logLevel: config.LOG_INFO,


    // enable / disable watching file and executing tests whenever any file changes
    autoWatch: true,


    // start these browsers
    // available browser launchers: https://npmjs.org/browse/keyword/karma-launcher
    browsers: ['Chrome'],


    // Continuous Integration mode
    // if true, Karma captures browsers, runs the tests and exits
    singleRun: false,

    client: {
      openui5: {
        config: {
          theme: 'sap_bluecrystal'
        }
      }
    }
  })
}

**Comment by matz3** [comment] 2016-01-18 10:47
Thanks @yonggao. This seems to be the same issue as in #2. Please see my comments there, especially https://github.com/SAP/karma-openui5/pull/2#issuecomment-170025760.
I close this one as a duplicate.

**Closed by matz3** 2016-01-18 10:47 UTC

**Comment by diegodossantos95** [comment] 2017-03-28 16:50
I was having the same issue. I had to change the mockserver.js file to fix it. @matz3 Can you release a new version with #2 fix?

**Comment by matz3** [comment] 2017-03-29 14:56
@diegodossantos95 I completely forgot to do the publish. I'm sorry. Just released [`0.2.2`](https://github.com/SAP/karma-openui5/releases/tag/0.2.2).

**Comment by diegodossantos95** [comment] 2017-03-29 15:57
@matz3 Thanks!
