### ISSUE TITLE
Mockserver problem

### ISSUE THREAD

**Issue by agrz** [SAP/karma-openui5#5] opened 2016-02-12 17:10 UTC
Hi,

I have problems getting the Opa tests run in Karma with using the integrated Mockserver.
I have a test project based on the UI5 tutorial. It can run Opa tests when embedding the tests using an iFrame and instanciate internal a Mockserver.
When trying to test the UI Components inside Karma runner and using the Karma OpenUI5 Mockserver I can start the UI, but no data is loaded. The Mockserver configuration is exactly the same as in the stand-alone mockserver and I see in the logs it inits its metadata, but no further requests are made to it.
I am a little stuck and not sure if this is a problem of my setup or a bug in the karma-openui5 runner.
You can see my configuration here: https://github.com/agrz/karma-openui5-maven-sample/tree/karma-openui5
Any help would be appreciated.
Thank You
Alexander

**Comment by matz3** [comment] 2016-03-08 17:30
I had a quick look into your project but it's quite hard to figure out where the issue is coming from.
The only thing I see which is that QUnit will be loaded twice (`karma-qunit` + `sap/ui/thirdparty/qunit.js`).

**Comment by matz3** [comment] 2016-04-08 15:23
Closing as there was no further response.

**Closed by matz3** 2016-04-08 15:23 UTC
