### ISSUE TITLE
karma-openui5 does not load properly

### ISSUE THREAD

**Issue by aitos** [SAP/karma-openui5#3] opened 2015-11-10 22:55 UTC
Hi I am using karma 0.13.15.

Attempting to load openUI5 and I get the following error:
 Uncaught Error: sap-ui-core.js: could not identify script tag!
 at C:<long path...>/resources/sap-ui-core.js:25

I only see the script tags that load openUI5 when going into the Karma debug runner.

Here is my config file; what am I doing wrong? ( I have stripped out my code and tests, while trying to narrow down the problem.  The result is the same with my code and test files included.)

// Karma configuration
// Generated on Fri Nov 06 2015 16:48:28 GMT-0500 (Eastern Standard Time)

module.exports = function(config) {
  config.set({

```
// base path that will be used to resolve all patterns (eg. files, exclude)
basePath: './',


// frameworks to use
// available frameworks: https://npmjs.org/browse/keyword/karma-adapter
frameworks: ["openui5"],


  files: [

      { pattern: 'build/tmp/bootRun/unpackedOpenuiRuntimeDependencies/resources/**/*', served: true, included: false, watched: false },


  ],

openui5: {
  path: 'build/tmp/bootRun/unpackedOpenuiRuntimeDependencies/resources/sap-ui-core.js',
  useMockServer: false
},

client: {
  openui5: {
      config: {
          theme: 'sap_bluecrystal',
          libs: 'sap.m',
          resourceroots: {
              'sap.m': 'build/tmp/bootRun/unpackedOpenuiRuntimeDependencies/resources/sap/m',
              //'my.namespace': '/base/src/my/namespace'
          },
          themeroots: {
              'sap_bluecrystal': 'build/tmp/bootRun/unpackedOpenuiRuntimeDependencies/resources/sap/m/themes/sap_bluecrystal'
          }

      }
  }
},

// list of files to exclude
exclude: [
],


// preprocess matching files before serving them to the browser
// available preprocessors: https://npmjs.org/browse/keyword/karma-preprocessor
preprocessors: {
    //'spec/sapui.html' : 'html2js'
},


// test results reporter to use
// possible values: 'dots', 'progress'
// available reporters: https://npmjs.org/browse/keyword/karma-reporter
reporters: ['progress'],


// web server port
port: 9876,


// enable / disable colors in the output (reporters and logs)
colors: true,


// level of logging
// possible values: config.LOG_DISABLE || config.LOG_ERROR || config.LOG_WARN || config.LOG_INFO || config.LOG_DEBUG
logLevel: config.LOG_DEBUG,


// enable / disable watching file and executing tests whenever any file changes
autoWatch: true,


// start these browsers
// available browser launchers: https://npmjs.org/browse/keyword/karma-launcher
browsers: ['Chrome'],


// Continuous Integration mode
// if true, Karma captures browsers, runs the tests and exits
singleRun: false,

// Concurrency level
// how many browser should be started simultanous
concurrency: Infinity
```

  })

}

**Comment by matz3** [comment] 2015-11-16 09:45
Did you already try to run this without the `resourceroots`/ `themeroots` configuration?
If you are using the extacted zip from http://openui5.org/download.html it should find the libraries and themes without any further configuration.

```js
resourceroots: {
    'sap.m': 'build/tmp/bootRun/unpackedOpenuiRuntimeDependencies/resources/sap/m',
    //'my.namespace': '/base/src/my/namespace'
},
themeroots: {
    'sap_bluecrystal': 'build/tmp/bootRun/unpackedOpenuiRuntimeDependencies/resources/sap/m/themes/sap_bluecrystal'
}
```

I could not reproduce the issue mentioned by you locally using the openui5-runtime-1.32.5.zip.

**Comment by matz3** [comment] 2016-01-20 09:18
Closing this for now. Please feel free to add comments if the issue is still relevant.

**Comment by themasch** [comment] 2018-06-11 09:00
I got the same issue just now. It happens because karma-openui5 appends a cachebuster string to the sap-ui-core.js script tag and the regex used in the lookup does not expect that:
```js
mMatch = sSrc.match(/(.*\/)sap-ui-core\.js$/i)
```

actual script tag karma generates: 
```html
<script type="text/javascript" src="/base/node_modules/@openui5/sap.ui.core/src/sap-ui-core.js?c130a88260d05608009c66b87e5a6c57c4f9fab0" crossorigin="anonymous"></script>
```

I'm not really shure why this does not happen in our other projects. Will investigate and keep you updated.

**Comment by matz3** [comment] 2018-10-01 13:04
@cevou fair enough. This needs to be addressed in the https://github.com/SAP/openui5 project. Feel free to file a pull-request.

**Comment by sebbi08** [comment] 2018-10-12 18:48
I just had the same problem and noticed that this only happens with "self-contained" builds if i build the normal build dose not have this script check

**Closed** 2018-12-10 09:23 UTC
Labels: bug
