### ISSUE TITLE
You need to include some adapter that implements __karma__.start method!

### ISSUE THREAD

**Issue by cschuff** [SAP/karma-openui5#6] opened 2016-06-21 08:33 UTC
Hi folks,

I'm trying to use your karma adapter but I keep getting the following error:
You need to include some adapter that implements __karma__.start method!

I'm on karma 0.13.22 and karma-openui5 0.2.1

If I debug it does load SAPUI5 and all my test dependencies:
```JS
sap.ui.define([
  "sap/ui/thirdparty/qunit",
  "sap/ui/qunit/qunit-css",
  "sap/ui/qunit/qunit-junit",
  "sap/ui/qunit/qunit-coverage"
], function () {

  "use strict";

  QUnit.test("Name of Test", function(assert) {
    // Setup the various states of the code you want to test and assert conditions.
    assert.equal(1, 1, "1 === 1");
    assert.ok(true, "true is truthy");
    assert.ok(1, "1 is also truthy");
    assert.ok([], "so is an empty array or object");
  });

});
```

It even executes my QUnit tests...

I don't get any test results nor in the browser neither in the console while getting the above error. Any idea what's the problem here?

Btw: I'm completly new to karma so may be this is really a simple thing to fix...

Thanks
Chris

**Comment by matz3** [comment] 2016-06-21 08:53
In case you use QUnit you also need to include the [karma-qunit](https://github.com/karma-runner/karma-qunit) adapter to have a connection between QUnit and karma.
The `karma-openui5` plugin does not cover that.

You should also not load QUnit from the UI5 thirdparty folder as the plugin loads it already.

**Comment by Zougi** [comment] 2016-07-25 07:43
I can reproduce this error with karma 1.x
Everything works OK on 0.13.22 though

**Comment by matz3** [comment] 2016-07-25 08:03
Thanks. I will again have a look into it.

**Comment by matz3** [comment] 2016-10-04 13:40
@Zougi could you please explain in more detail how you were able to reproduce this? I would like to have a look into it. Closing this for now again..

**Closed by matz3** 2016-10-04 13:40 UTC
Labels: question

**Comment by Zougi** [comment] 2016-10-05 20:17
I do not have the jenkins build history because it has been erased by some admin Grrrrr.. However I can give you better than that: the project. It's on sap's github enterprise under organization WebI, repository wing. You might be able to reproduce the error by synchronizing the project with commit hash 79ae8d66625b69d7215f1a20e4ae1fd3d930cb2a. We were using nodejs 4.2.2 at the time.
